---
threads: 6
dpi: 50

frames_per_day: 4
frames_for_line: 30

point_decay_days: 15
point_size: 4
transparency_alpha: 1

#date format Year-Month-Day
start_date: 2014-09-01
end_date: 2022-05-01

### Region
title_format_region: "%d %b %Y"

region_json: italy_provinces.geojson
municipalities_json: R_18_R_19.geojson
region_cases: region_cases.csv
region_transfers_file: transfers.csv
milestones: milestones.csv

### World
title_format_world: "%Y"
world_json: world.json
world_cases: world_cases.csv
centroids_file: ../../depot/centroids.csv
world_transfers_file: transfers.csv
