---
threads: 6
dpi: 50

frames_per_day: 1
frames_for_line: 30

point_decay_days: 15
point_size: 4
transparency_alpha: 1

### Region
title_format_region: %d %b %Y"

### World
title_format_world: "%Y"
#date format Year-Month-Day
start_date: 1997-01-01
end_date: 2002-12-31
world_json: world.json
world_cases: world_cases.csv
centroids_file: ../../depot/centroids.csv
transfers_file: transfers.csv
